### ISSUE TITLE
Run make all term in Docker image

### ISSUE THREAD

**Issue by antmerlino** [RIOT-OS/riotdocker#25] opened 2017-01-18 18:41 UTC
Not sure if this is supposed to work already, or if it is an unsupported feature currently.  I am trying to run make all term on one of the tutorials using the Docker image.  It builds correctly but fails to run with this error:

`native_cpu_init: getcontext: Operation not permitted`

It would be awesome if I were to be able to build and run an application on the "native" target from a single docker command.   It seems that this is a close possibility unless there is something I don't understand about limitations of docker.

**Comment by cgundogan** [comment] 2017-01-18 19:07
@antmerlino can you try `BUILD_IN_DOCKER=1 make all term`?

**Comment by antmerlino** [comment] 2017-01-18 19:19
Are you suggesting to have make locally on the host and invoke `BUILD_IN_DOCKER=1 make all term' which would build inside the docker but then run the binary on the host os?

What I'd like to do is invoke and run within the docker container.  Like so:

`docker run -it -u $UID -v /$(dirname $(pwd)):/data/riotbuild riotbuild make -C task-02 all term'

**Comment by kaspar030** [comment] 2017-01-18 19:20
@antmerlino Try adding ```--security-opt seccomp=unconfined```.

The problem is that native RIOT compiles to a 32bit binary which uses get_context(), which is somehow blocked by the security options.

**Comment by antmerlino** [comment] 2017-01-18 19:23
@kaspar030 AWESOME! It worked! Being able to build and run by simply invoking a Docker container is  very powerful for me.

Those options should probably be added to the docs on the other repo.  Let me know if you'd like me to do that.

**Comment by tingxin** [comment] 2017-06-27 10:43
Still don't know how to use this docker, could anyone kindly give a tutorials?

**Comment by gebart** [comment] 2017-06-27 11:07
The Docker support is integrated into the RIOT build system, to build in docker instead of with your systern compiler simply add `BUILD_IN_DOCKER=1` to the make command:

```
cd examples/hello_world
BUILD_IN_DOCKER=1 make
```

It works for flashing as well; the compilation will run from docker, but the flash tool (e.g. Openocd)  will run directly on your host system

```
BUILD_IN_DOCKER=1 make flash
```

If you want to update your docker image to the latest version you can use the regular docker pull command:

```
docker pull riot/riotbuild
```

**Comment by gebart** [comment] 2017-06-27 11:10
If you want to always use docker to build you can add the line `export BUILD_IN_DOCKER=1` to your `~/.profile`

**Comment by smlng** [comment] 2018-10-10 09:45
this is resolved with @kaspar030  comment: https://github.com/RIOT-OS/riotdocker/issues/25#issuecomment-273573127 , right?

**Comment by miri64** [comment] 2019-01-16 14:35
I'd say so.

**Closed by miri64** 2019-01-16 14:35 UTC
Labels: question
